version: 2.1

orbs:
  python: cjw296/python-ci@2.1

common: &common
  jobs:

    - python/pip-run-tests:
        matrix:
          parameters:
            image:
              - circleci/python:3.6
              - circleci/python:3.9

    - python/coverage:
        name: coverage
        image: circleci/python:3.9
        requires:
          - python/pip-run-tests

    - python/release:
        name: release
        config: .carthorse.yml
        requires:
          - coverage
        filters:
          branches:
            only: master

workflows:
  push:
    <<: *common
  periodic:
    <<: *common
    triggers:
      - schedule:
          cron: "0 0 * * 2"
          filters:
            branches:
              only: master
